### ISSUE TITLE
ImportError: No module named htmlunit ; however using jython and JARs are processed 

### ISSUE THREAD

**Issue by ghost** [adamdoupe/enemy-of-the-state#1]
This issue happens both on Mac OS X, and on Kali Linux.

Traceback (most recent call last):
  File "crawler2.py", line 7, in <module>
    import htmlunit
ImportError: No module named htmlunit

---

root@kali:~/enemy-of-the-state# jython crawler2.py 
_sys-package-mgr_: processing new jar, '/usr/share/java/jython-2.5.2.jar'
_sys-package-mgr_: processing new jar, '/usr/share/maven-repo/org/antlr/antlr-runtime/3.2/antlr-runtime-3.2.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/stringtemplate-3.2.1.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/antlr.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/asm3-3.3.2.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/asm3-commons-3.3.2.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/asm3-tree-3.3.2.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/constantine-0.7.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/guava-11.0.2.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/jsr305-0.1~+svn49.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/jnr-posix-1.1.4.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/jaffl-0.5.4.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/jffi-1.0.2.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jffi/jffi-native.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/jnr-x86asm-0.1.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/jnr-netdb.jar'
_sys-package-mgr_: processing new jar, '/usr/share/maven-repo/org/livetribe/livetribe-jsr223/2.0.6/livetribe-jsr223-2.0.6.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/jline-1.0.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/libreadline-java-0.8.0.1.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-common/jre/lib/resources.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-i386/jre/lib/rt.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-i386/jre/lib/jsse.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-i386/jre/lib/jce.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-i386/jre/lib/charsets.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-i386/jre/lib/rhino.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-common/jre/lib/ext/dnsns.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-common/jre/lib/ext/localedata.jar'
_sys-package-mgr_: processing new jar, '/usr/share/java/java-atk-wrapper.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-common/jre/lib/ext/pulse-java.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-common/jre/lib/ext/sunpkcs11.jar'
_sys-package-mgr_: processing new jar, '/usr/lib/jvm/java-6-openjdk-common/jre/lib/ext/sunjce_provider.jar'
Traceback (most recent call last):
  File "crawler2.py", line 7, in <module>
    import htmlunit
ImportError: No module named htmlunit
root@kali:~/enemy-of-the-state#  export JYTHONPATH=./lib/apache-mime4j-0.6.jar:./lib/commons-codec-1.4.jar:./lib/commons-collections-3.2.1.jar:./lib/commons-io-1.4.jar:./lib/commons-lang-2.4.jar:./lib/commons-logging-1.1.1.jar:./lib/cssparser-0.9.5.jar:./lib/htmlunit-2.8.jar:./lib/htmlunit-core-js-2.8.jar:./lib/httpclient-4.0.1.jar:./lib/httpcore-4.0.1.jar:./lib/httpmime-4.0.1.jar:./lib/nekohtml-1.9.14.jar:./lib/sac-1.3.jar:./lib/serializer-2.7.1.jar:./lib/xalan-2.7.1.jar:./lib/xercesImpl-2.9.1.jar:./lib/xml-apis-1.3.04.jar
root@kali:~/enemy-of-the-state# jython crawler2.py 
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/apache-mime4j-0.6.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/commons-codec-1.4.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/commons-collections-3.2.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/commons-io-1.4.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/commons-lang-2.4.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/commons-logging-1.1.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/cssparser-0.9.5.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/htmlunit-2.8.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/htmlunit-core-js-2.8.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/httpclient-4.0.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/httpcore-4.0.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/httpmime-4.0.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/nekohtml-1.9.14.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/sac-1.3.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/serializer-2.7.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/xalan-2.7.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/xercesImpl-2.9.1.jar'
_sys-package-mgr_: processing new jar, '/root/enemy-of-the-state/lib/xml-apis-1.3.04.jar'
Traceback (most recent call last):
  File "crawler2.py", line 7, in <module>
    import htmlunit
ImportError: No module named htmlunit

**Comment by ghost** [comment]
diverse additional information, may be helpful:

# export

declare -x JYTHONPATH="./lib/apache-mime4j-0.6.jar:./lib/commons-codec-1.4.jar:./lib/commons-collections-3.2.1.jar:./lib/commons-io-1.4.jar:./lib/commons-lang-2.4.jar:./lib/commons-logging-1.1.1.jar:./lib/cssparser-0.9.5.jar:./lib/htmlunit-2.8.jar:./lib/htmlunit-core-js-2.8.jar:./lib/httpclient-4.0.1.jar:./lib/httpcore-4.0.1.jar:./lib/httpmime-4.0.1.jar:./lib/nekohtml-1.9.14.jar:./lib/sac-1.3.jar:./lib/serializer-2.7.1.jar:./lib/xalan-2.7.1.jar:./lib/xercesImpl-2.9.1.jar:./lib/xml-apis-1.3.04.jar"

root@kali:~/enemy-of-the-state# python --version
Python 2.7.3
root@kali:~/enemy-of-the-state# jython --version
Jython 2.5.2
root@kali:~/enemy-of-the-state# git status

# On branch master

nothing to commit (working directory clean)

**Comment by ghost** [comment]
You must have checked out the Master branch instead of the Jython branch.

"The git master branch is for jcc and the jython branch is for jython."

**Comment by adamdoupe** [comment]
That's a good point Alex.

Fabien, is this issue still relevant?
